# front_laser
- ros_topic_name: "/summit/front_laser/scan"
  gz_topic_name: "/summit/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS  # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

# rear_laser
- ros_topic_name: "/summit/rear_laser/scan"
  gz_topic_name: "/summit/rear_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS

# front_rgbd_camera/color
- ros_topic_name: "/summit/front_rgbd_camera/color/image_raw"
  gz_topic_name: "/summit/front_rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS

# front_rgbd_camera/color/camera_info
- ros_topic_name: "/summit/front_rgbd_camera/color/camera_info"
  gz_topic_name: "/summit/front_rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS

# front_rgbd_camera/depth
- ros_topic_name: "/summit/front_rgbd_camera/depth/image_raw"
  gz_topic_name: "/summit/front_rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS

# front_rgbd_camera/depth/camera_info
- ros_topic_name: "/summit/front_rgbd_camera/depth/camera_info"
  gz_topic_name: "/summit/front_rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS

# front_rgbd_camera/depth/image_raw/points
- ros_topic_name: "/summit/front_rgbd_camera/points"
  gz_topic_name: "/summit/front_rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: true                # Default "false"
  direction: GZ_TO_ROS

# robotnik_base_control/odom
# - ros_topic_name: "/robotnik_base_control/odom"
- ros_topic_name: "/summit/odom"
  gz_topic_name: "/model/summit/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS

# /summit/joint_states
- ros_topic_name: "/summit/joint_states"
  gz_topic_name: "/summit/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS

# /summit/robotnik_base_control/cmd_vel_unstamped
# - ros_topic_name: "/summit/robotnik_base_control/cmd_vel_unstamped"
- ros_topic_name: "/summit/cmd_vel"
  gz_topic_name: "/model/summit/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: ROS_TO_GZ

# /summit/tf
- ros_topic_name: "/summit/tf"
  gz_topic_name: "/model/summit/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS

# /clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS
